<?php
/**
 * @var $this Mzeis_Documentation_Block_Adminhtml_Page_View
 */

/**
 * @var $_page Mzeis_Documentation_Model_Page
 */
$_page = $this->getPage();
?>
<div class="content-header">
    <h3><a href="<?php echo $this->getHomepageUrl(); ?>" class="content-header-link"><?php echo $this->__('Documentation') ?></a> &gt; <?php echo $this->escapeHtml($_page->getName()); ?></h3>
    <p class="form-buttons">
        <?php echo $this->getChildHtml('edit_button'); ?>
    </p>
</div>

<div class="mzeis-documentation page-container">
    <?php if ($_page->getId()): ?>
        <?php echo $this->renderContent(); ?>
        <div class="documentation-meta-info">
            <p><?php echo $this->__('Created: %s', $this->printDate($_page->getCreatedAt())); ?></p>
            <p><?php if($_page->getCreatedAt() != $_page->getUpdatedAt()) { echo $this->__('Updated: %s', $this->printDate($_page->getUpdatedAt())); } ?></p>
        </div>
    <?php else: ?>
        <?php echo $this->__('This page is empty.'); ?>
        <?php if ($this->isAllowedEdit()): echo $this->__('<a href="%s">Add content</a>', Mage::helper('mzeis_documentation/page')->getEditUrl($_page->getName())); endif; ?>
    <?php endif; ?>
</div>
