<?php
/**
 * @var $this Mzeis_Documentation_Block_Adminhtml_Page_List
 */
$_collection = $this->getOrphanPagesCollection();
$_helper = Mage::helper('mzeis_documentation/page');
?>
<div class="content-header">
    <h3><?php echo $this->__('Orphan pages'); ?></h3>
</div>
<div class="mzeis-documentation-container">
<?php if ($_collection->getSize() > 0): ?>
    <p><?php echo $this->__('%s page(s) not linked by other pages:', $_collection->getSize()); ?></p>
    <ol>
    <?php foreach ($_collection as $_page): ?>
        <li><a href="<?php echo $_helper->getViewUrl($_page->getName()); ?>"><?php echo $this->escapeHtml($_page->getName()); ?></a></li>
    <?php endforeach; ?>
    </ol>
<?php else: ?>
    <p><?php echo $this->__('There are no pages without links to it.'); ?></p>
<?php endif; ?>
</div>
